sudo: required
services: 
  - docker

before_install:
  - docker build -t yesuramu/docker-create -f Dockerfile.dev .

script:
  - docker run -e CI=true yesuramu/docker-create npm run test -- --coverage
